#!/bin/bash
# Quick Seed Commands for LEXA Lifestyle

echo "🌱 LEXA Lifestyle - Quick Seed Commands"
echo "========================================"
echo ""
echo "Choose an option:"
echo ""
echo "1. Seed Everything (Full database)"
echo "   python seed_master.py --mode all"
echo ""
echo "2. Seed Core Only (Solutions, Services, Brands)"
echo "   python seed_master.py --mode core"
echo ""
echo "3. Seed Packages Only (Package builder system)"
echo "   python seed_master.py --mode packages"
echo ""
echo "4. Individual Seeds:"
echo "   - Solutions:    python seed_all_solutions.py"
echo "   - Services:     python seed_all_services.py"
echo "   - Packages:     python seed_smart_home_packages.py"
echo "   - Apartments:   python seed_developer_apartments.py"
echo "   - Enhancements: python seed_package_enhancements.py"
echo "   - Brands:       python seed_brand_options.py"
echo ""
echo "📚 Full documentation: See SEEDING_GUIDE.md"
echo ""
